export default {
  backgroundWhite: "aliceblue",
  backgroundDark: "#020202",
  fontColor: "aliceblue",
  borderColor: "darkgrey",
  primary: "#D1D51A",
  secondary: "#FCF1A1",
  trackFalse: "#D67577",
  trackTrue: "#CCC",
  disabled: "#68D48A",
  success: "green",
  failure: "#F10045",
  switchTrue: "#f0543C",
  switchFalse: "#f4f3f4",
}